Что-то 2

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -53,22 +53,54 @@ jobs:
         run: |
           echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
 
+      - name: Setup environment and dependencies
+        run: |
+          sudo apt update
+          sudo apt install -y gettext-base
+
+      - name: Debug variables before substitution
+        run: |
+          echo "APP_VERSION = $APP_VERSION"
+          echo "IMAGE_NAME = $IMAGE_NAME"
+          which envsubst || echo "envsubst not found"
+
       - name: Generate deployment.yaml from template
         run: |
-
           export APP_VERSION=${{ env.APP_VERSION }}
           export IMAGE_NAME=${{ env.IMAGE_NAME }}
           envsubst '${IMAGE_NAME} ${APP_VERSION}' < k8s/deployment.template.yaml > k8s/deployment.yaml
 
       - name: Show generated deployment.yaml
         run: |
+          echo "Содержимое k8s/deployment.yaml:"
           cat k8s/deployment.yaml
+
+      - name: Install kubectl
+        run: |
+          curl -LO "https://dl.k8s.io/release/$(curl  -LSs https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" 
+          chmod +x kubectl
+          sudo mv kubectl /usr/local/bin/
 
       - name: Setup kubeconfig
         run: |
           mkdir -p ~/.kube
           echo "${{ secrets.KUBE_CONFIG_DATA }}" > ~/.kube/config
-          
+
       - name: Apply manifests
         run: |
           kubectl apply -f k8s/
+
+      - name: Wait for rollout
+        run: |
+          kubectl rollout status deployment/test-app --timeout=60s
+
+      - name: Check current image in Deployment
+        run: |
+          CURRENT_IMAGE=$(kubectl get deployment test-app -o jsonpath='{.spec.template.spec.containers[0].image}')
+          echo "🚀 Текущий образ в Kubernetes: $CURRENT_IMAGE"
+          if [[ "$CURRENT_IMAGE" == "*${APP_VERSION}" ]]; then
+            echo "✅ Версия успешно обновлена на $APP_VERSION"
+          else
+            echo "❌ Ошибка: ожидается $IMAGE_NAME:$APP_VERSION, найдено $CURRENT_IMAGE"
+            exit 1
+          fi
